[build]
builder = "DOCKERFILE"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[service]
name = "cmms-api-v2"

[build.steps]
preBuild = "echo 'Starting Docker build for CMMS...'" 