services:
  - type: web
    name: cmms-api
    env: python
    buildCommand: bash build.sh
    startCommand: cd backend && gunicorn --bind 0.0.0.0:$PORT --workers 1 --worker-class uvicorn.workers.UvicornWorker --timeout 120 app.main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0 